//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveAndPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationBarMenus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationBarMenus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveAndPlay.Resources.ApplicationBarMenus", typeof(ApplicationBarMenus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBar_AboutMenu {
            get {
                return ResourceManager.GetString("AppBar_AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save media.
        /// </summary>
        public static string AppBar_AddMenu {
            get {
                return ResourceManager.GetString("AppBar_AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto title.
        /// </summary>
        public static string AppBar_AutoTitleButton {
            get {
                return ResourceManager.GetString("AppBar_AutoTitleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clean.
        /// </summary>
        public static string AppBar_ClearMenu {
            get {
                return ResourceManager.GetString("AppBar_ClearMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string AppBar_DeleteButton {
            get {
                return ResourceManager.GetString("AppBar_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string AppBar_DownloadButton {
            get {
                return ResourceManager.GetString("AppBar_DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        public static string AppBar_FavoriteAdditionMenu {
            get {
                return ResourceManager.GetString("AppBar_FavoriteAdditionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string AppBar_FavoritesMenu {
            get {
                return ResourceManager.GetString("AppBar_FavoritesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is audio.
        /// </summary>
        public static string AppBar_IsAudioButton {
            get {
                return ResourceManager.GetString("AppBar_IsAudioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is video.
        /// </summary>
        public static string AppBar_IsVideoButton {
            get {
                return ResourceManager.GetString("AppBar_IsVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string AppBar_PreviousButton {
            get {
                return ResourceManager.GetString("AppBar_PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBar_RefreshButton {
            get {
                return ResourceManager.GetString("AppBar_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset.
        /// </summary>
        public static string AppBar_ResetButton {
            get {
                return ResourceManager.GetString("AppBar_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBar_SaveButton {
            get {
                return ResourceManager.GetString("AppBar_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scan.
        /// </summary>
        public static string AppBar_ScanButton {
            get {
                return ResourceManager.GetString("AppBar_ScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected mode.
        /// </summary>
        public static string AppBar_SettingsMenu {
            get {
                return ResourceManager.GetString("AppBar_SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string AppBar_SigninButton {
            get {
                return ResourceManager.GetString("AppBar_SigninButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string AppBar_SignoutButton {
            get {
                return ResourceManager.GetString("AppBar_SignoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tag.
        /// </summary>
        public static string AppBar_TagButton {
            get {
                return ResourceManager.GetString("AppBar_TagButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validate.
        /// </summary>
        public static string AppBar_ValidateButton {
            get {
                return ResourceManager.GetString("AppBar_ValidateButton", resourceCulture);
            }
        }
    }
}
