//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveAndPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DownloadList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DownloadList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveAndPlay.Resources.DownloadList", typeof(DownloadList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers bound to Save &amp; Play are currently in progress. These will be interrupted if you quit Save &amp; Play. Are you sure you want to continue?.
        /// </summary>
        public static string ActiveForegroundTransferLabel {
            get {
                return ResourceManager.GetString("ActiveForegroundTransferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelMenuItem {
            get {
                return ResourceManager.GetString("CancelMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Enum_TransferStatus_Cancelled {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled, the App didn&apos;t stay active.
        /// </summary>
        public static string Enum_TransferStatus_CancelledByQuit {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_CancelledByQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Enum_TransferStatus_Completed {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Enum_TransferStatus_Error {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_TransferStatus_None {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Enum_TransferStatus_Paused {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring.
        /// </summary>
        public static string Enum_TransferStatus_Transferring {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Transferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Enum_TransferStatus_Unknown {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Enum_TransferStatus_Waiting {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to be plugged in to charger.
        /// </summary>
        public static string Enum_TransferStatus_WaitingForExternalPower {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_WaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery saver mode enabled, waiting to be plugged in to charger.
        /// </summary>
        public static string Enum_TransferStatus_WaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_WaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting 3G or faster connection.
        /// </summary>
        public static string Enum_TransferStatus_WaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_WaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting WiFi connection.
        /// </summary>
        public static string Enum_TransferStatus_WaitingForWiFi {
            get {
                return ResourceManager.GetString("Enum_TransferStatus_WaitingForWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no download in progress, press + to start a new one.
        /// </summary>
        public static string NoDownload {
            get {
                return ResourceManager.GetString("NoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed : .
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : .
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one or more file transfers waiting for external power. Plug in your device to charger to continue transferring.
        /// </summary>
        public static string WaitingForExternalPower {
            get {
                return ResourceManager.GetString("WaitingForExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one or more file transfers waiting for external power. Plug in your device to charger or disable Battery Saver Mode to continue transferring&amp;.
        /// </summary>
        public static string WaitingForExternalPowerDueToBatterySaverMode {
            get {
                return ResourceManager.GetString("WaitingForExternalPowerDueToBatterySaverMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one or more file transfers waiting for a 3G or faster data connection.
        /// </summary>
        public static string WaitingForNonVoiceBlockingNetwork {
            get {
                return ResourceManager.GetString("WaitingForNonVoiceBlockingNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have one or more file transfers waiting for a Wi-Fi connection. Connect your device to a Wi-Fi network to continue transferring.
        /// </summary>
        public static string WaitingForWiFi {
            get {
                return ResourceManager.GetString("WaitingForWiFi", resourceCulture);
            }
        }
    }
}
