//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveAndPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MusicList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MusicList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveAndPlay.Resources.MusicList", typeof(MusicList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string AlbumLabel {
            get {
                return ResourceManager.GetString("AlbumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album(s).
        /// </summary>
        public static string AlbumSubtitle {
            get {
                return ResourceManager.GetString("AlbumSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string AlbumTitle {
            get {
                return ResourceManager.GetString("AlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string ArtistLabel {
            get {
                return ResourceManager.GetString("ArtistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArtistTitle {
            get {
                return ResourceManager.GetString("ArtistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio media.
        /// </summary>
        public static string AudioMediaTitle {
            get {
                return ResourceManager.GetString("AudioMediaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the item &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to send &apos;{0}&apos; to the video library?.
        /// </summary>
        public static string ConfirmSendToVideo {
            get {
                return ResourceManager.GetString("ConfirmSendToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to play the selected audio file.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string MediaAlbumLabel {
            get {
                return ResourceManager.GetString("MediaAlbumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string MediaArtistLabel {
            get {
                return ResourceManager.GetString("MediaArtistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect media.
        /// </summary>
        public static string MediaProtectedLabel {
            get {
                return ResourceManager.GetString("MediaProtectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MediaTitleLabel {
            get {
                return ResourceManager.GetString("MediaTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist.
        /// </summary>
        public static string NewPlaylist {
            get {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The album list is empty, go to the download dedicated page to add new songs.
        /// </summary>
        public static string NoAlbum {
            get {
                return ResourceManager.GetString("NoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artist list is empty, go to the download dedicated page to add new songs.
        /// </summary>
        public static string NoArtist {
            get {
                return ResourceManager.GetString("NoArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist list is empty, press + to add new ones.
        /// </summary>
        public static string NoPlaylist {
            get {
                return ResourceManager.GetString("NoPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist list is empty, go to the playlist dedicated page to add new ones.
        /// </summary>
        public static string NoPlaylistInAudioMedia {
            get {
                return ResourceManager.GetString("NoPlaylistInAudioMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song list is empty, go to the download dedicated page to add new ones.
        /// </summary>
        public static string NoSong {
            get {
                return ResourceManager.GetString("NoSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This playlist is empty, press a song and assign playlists to it.
        /// </summary>
        public static string NoSongInPlaylist {
            get {
                return ResourceManager.GetString("NoSongInPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion of &apos;{0}&apos; audio media failed. Maybe it is currently playing..
        /// </summary>
        public static string PlayingError {
            get {
                return ResourceManager.GetString("PlayingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string PlaylistLabel {
            get {
                return ResourceManager.GetString("PlaylistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string PlaylistTitle {
            get {
                return ResourceManager.GetString("PlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesLabel {
            get {
                return ResourceManager.GetString("PropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string SongLabel {
            get {
                return ResourceManager.GetString("SongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song(s).
        /// </summary>
        public static string SongSubtitle {
            get {
                return ResourceManager.GetString("SongSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to read tags from the selected audio file.
        /// </summary>
        public static string TagError {
            get {
                return ResourceManager.GetString("TagError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio library.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title/name field must not be empty.
        /// </summary>
        public static string TitleMustBeFilled {
            get {
                return ResourceManager.GetString("TitleMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UndefinedLabel {
            get {
                return ResourceManager.GetString("UndefinedLabel", resourceCulture);
            }
        }
    }
}
