//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveAndPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewDownload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewDownload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveAndPlay.Resources.NewDownload", typeof(NewDownload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App has to stay active, do not quit, do not go into sleep mode.
        /// </summary>
        public static string ActiveAppMandatoryLabel {
            get {
                return ResourceManager.GetString("ActiveAppMandatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or enter an URL.
        /// </summary>
        public static string AddressBarHint {
            get {
                return ResourceManager.GetString("AddressBarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound.
        /// </summary>
        public static string BackgroundTransferMode {
            get {
                return ResourceManager.GetString("BackgroundTransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer unbound from Save &amp; Play, keep downloading even if Save &amp; Play is no longer running..
        /// </summary>
        public static string BackgroundTransferModeLabel {
            get {
                return ResourceManager.GetString("BackgroundTransferModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to browse in this folder, maybe the connection has been lost.
        /// </summary>
        public static string BrowseFolderFailedLabel {
            get {
                return ResourceManager.GetString("BrowseFolderFailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 3G or faster data connection is required.
        /// </summary>
        public static string Cellular3GMandatoryLabel {
            get {
                return ResourceManager.GetString("Cellular3GMandatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A 3G or faster data connection is required.
        /// </summary>
        public static string Cellular3GMandatoryLabelLong {
            get {
                return ResourceManager.GetString("Cellular3GMandatoryLabelLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data connection is required.
        /// </summary>
        public static string ConnectionMandatoryLabel {
            get {
                return ResourceManager.GetString("ConnectionMandatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data connection is required.
        /// </summary>
        public static string ConnectionMandatoryLabelLong {
            get {
                return ResourceManager.GetString("ConnectionMandatoryLabelLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data connection is required.
        /// </summary>
        public static string ConnectionRequiredLabel {
            get {
                return ResourceManager.GetString("ConnectionRequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadRequirementsFailed {
            get {
                return ResourceManager.GetString("DownloadRequirementsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name is already being downloaded.
        /// </summary>
        public static string DownloadSameName {
            get {
                return ResourceManager.GetString("DownloadSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to download.
        /// </summary>
        public static string DownloadValidation {
            get {
                return ResourceManager.GetString("DownloadValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download warning.
        /// </summary>
        public static string DownloadWarning {
            get {
                return ResourceManager.GetString("DownloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign in to your Dropbox account, please check your network connection and try again..
        /// </summary>
        public static string DropboxLoginFailed {
            get {
                return ResourceManager.GetString("DropboxLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox.
        /// </summary>
        public static string DropboxTitle {
            get {
                return ResourceManager.GetString("DropboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is empty or does not contain any Save &amp; Play supported media files.
        /// </summary>
        public static string EmptyFolderLabel {
            get {
                return ResourceManager.GetString("EmptyFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a link just above and validate.
        /// </summary>
        public static string EnterInstructionsLabel {
            get {
                return ResourceManager.GetString("EnterInstructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device must be plugged in to charger.
        /// </summary>
        public static string ExternalPowerMandatoryLabel {
            get {
                return ResourceManager.GetString("ExternalPowerMandatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device must be plugged in to charger.
        /// </summary>
        public static string ExternalPowerMandatoryLabelLong {
            get {
                return ResourceManager.GetString("ExternalPowerMandatoryLabelLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add favorite.
        /// </summary>
        public static string FavoriteAddition {
            get {
                return ResourceManager.GetString("FavoriteAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your favorite has been successfully added.
        /// </summary>
        public static string FavoriteAdditionSuccess {
            get {
                return ResourceManager.GetString("FavoriteAdditionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        public static string FavoriteInvalidURL {
            get {
                return ResourceManager.GetString("FavoriteInvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name must be specified to save a favorite.
        /// </summary>
        public static string FavoriteNameRequired {
            get {
                return ResourceManager.GetString("FavoriteNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound.
        /// </summary>
        public static string ForegroundTransferMode {
            get {
                return ResourceManager.GetString("ForegroundTransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer bound to Save &amp; Play, keep downloading as long as Save &amp; Play is running..
        /// </summary>
        public static string ForegroundTransferModeLabel {
            get {
                return ResourceManager.GetString("ForegroundTransferModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information message.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple link.
        /// </summary>
        public static string ManualURLTitle {
            get {
                return ResourceManager.GetString("ManualURLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of background file transfer requests for this application has been exceeded.
        /// </summary>
        public static string MaximumDownloadReached {
            get {
                return ResourceManager.GetString("MaximumDownloadReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new download has started, you can monitor it from the download dedicated page
        ///.
        /// </summary>
        public static string NewDownloadStarted {
            get {
                return ResourceManager.GetString("NewDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough free space on your device to download {0}.
        /// </summary>
        public static string NotEnoughFreeSpace {
            get {
                return ResourceManager.GetString("NotEnoughFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title.
        /// </summary>
        public static string NoTitleSpecified {
            get {
                return ResourceManager.GetString("NoTitleSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode could not be decoded.
        /// </summary>
        public static string QRCodeFailed {
            get {
                return ResourceManager.GetString("QRCodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string RootDirectoryLabel {
            get {
                return ResourceManager.GetString("RootDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a QRCode to get a link and validate.
        /// </summary>
        public static string ScanInstructionsLabel {
            get {
                return ResourceManager.GetString("ScanInstructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign in to your SkyDrive account, please check your network connection and try again..
        /// </summary>
        public static string SkydriveLoginFailed {
            get {
                return ResourceManager.GetString("SkydriveLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive.
        /// </summary>
        public static string SkydriveTitle {
            get {
                return ResourceManager.GetString("SkydriveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the media title.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start file transfer.
        /// </summary>
        public static string TransferAdditionFailed {
            get {
                return ResourceManager.GetString("TransferAdditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer mode.
        /// </summary>
        public static string TransferMode {
            get {
                return ResourceManager.GetString("TransferMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduced from the chosen transfer mode and the media size ({0}).
        /// </summary>
        public static string TransferModeLabel {
            get {
                return ResourceManager.GetString("TransferModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer requirements.
        /// </summary>
        public static string TransferRequirementsLabel {
            get {
                return ResourceManager.GetString("TransferRequirementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save this file?.
        /// </summary>
        public static string URLChoice {
            get {
                return ResourceManager.GetString("URLChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link could not be loaded.
        /// </summary>
        public static string URLInvalid {
            get {
                return ResourceManager.GetString("URLInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link doesn&apos;t target a Save &amp; Play supported media file or could not be accessed.
        /// </summary>
        public static string URLKO {
            get {
                return ResourceManager.GetString("URLKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string URLLabel {
            get {
                return ResourceManager.GetString("URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRCode.
        /// </summary>
        public static string URLSelectorQRCodeTitle {
            get {
                return ResourceManager.GetString("URLSelectorQRCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks in progress.
        /// </summary>
        public static string URLValidation {
            get {
                return ResourceManager.GetString("URLValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A validation is already in progress.
        /// </summary>
        public static string URLValidationInProgress {
            get {
                return ResourceManager.GetString("URLValidationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-Fi connection required.
        /// </summary>
        public static string WifiMandatoryLabel {
            get {
                return ResourceManager.GetString("WifiMandatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Wi-Fi connection is required.
        /// </summary>
        public static string WifiMandatoryLabelLong {
            get {
                return ResourceManager.GetString("WifiMandatoryLabelLong", resourceCulture);
            }
        }
    }
}
